Swagger docs
Token must be active AND belong to a user of role ADMIN
---
consumes:
    - application/json
parameters:
    - name: body
        in: body
        schema:
        type: object
        required:
            - username
        properties:
            username:
                type: string
            password:
                type: string
            role:
                type: string
    - name: Authorization
        in: header
        schema:
        type: object
        required:
            - access_token
        properties:
            access_token:
                type: string
responses:
    200:
        description: Edit user
        schema:
            id: User
            properties:
            username:
            type: string
            description: The names of the user
            default: Default Username
    500:
        description: Error editing user
        schema:
            id: User
            properties:
                message:
                    type: string
                    description: Error description
                    default: Default
